apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team     #add a team proj
  namespace: argocd
spec:
  destinations:
  - namespace: team-*  #Specifies the namespace where applications can be deployed.
    server: '*'  #Specifies the Kubernetes API server where applications can be deployed
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
  sourceRepos:
  - https://github.com/bingarthur/argocd.git #Specifies a list of Git repositories that contain the source code of applications managed by this project.

  roles:
  - name: team-admin
    policies:
    - p, proj:team:team-admin, applications, *, team/*, allow
  - name: ci-role
    description: Create and Sync apps
    policies:
    - p, proj:team:ci-role, applications, sync, team/*, allow
    - p, proj:team:ci-role, applications, get,  team/*, allow
    - p, proj:team:ci-role, applications, create, team/*, allow
    - p, proj:team:ci-role, applications, update, team/*, allow
    - p, proj:team:ci-role, applications, delete, team/*, allow

#apply this yaml to create a new project , called team
# argocd login 127.0.0.1:8080
# get a token by ci-role
#argocd proj role create-token team ci-role -e 1d
# add this role to github secret 